### PR TITLE
Fixing race condition with reading and writing to state tracker elementID

### LINKED ISSUE #491: greyswizzled_setState: crash when task completes with error
It seems like `- (void)greyswizzled_setState:(NSURLSessionTaskState)newState` sometimes crashes with EXC_BAD_ACCESS(code=EXC_i386_GPFLT) when NSURLSession task completes with error.

```
(lldb) po NSThread.callStackSymbols
<_NSCallStackArray 0x60000285e510>(
0   ???                                 0x0000000121dcecbc 0x0 + 4863093948,
1   AppName                       0x00000001004ddf40 main + 0,
2   CFNetwork                           0x00000001098024c7 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.185 + 36,
3   Foundation                          0x0000000104dd8237 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7,
4   Foundation                          0x0000000104dd7f3b -[NSBlockOperation main] + 101,
5   Foundation                          0x0000000104dd66f7 -[__NSOperationInternal _start:] + 627,
6   Foundation                          0x0000000104dd247c __NSOQSchedule_f + 198,
7   libdispatch.dylib                   0x000000010a86c792 _dispatch_client_callout + 8,
8   libdispatch.dylib                   0x000000010a852237 _dispatch_queue_serial_drain + 1022,
9   libdispatch.dylib                   0x000000010a85298f _dispatch_queue_invoke + 1053,
10  libdispatch.dylib                   0x000000010a854899 _dispatch_root_queue_drain + 813,
11  libdispatch.dylib                   0x000000010a85450d _dispatch_worker_thread3 + 113,
12  libsystem_pthread.dylib             0x000000010ac00712 _pthread_wqthread + 1299,
13  libsystem_pthread.dylib             0x000000010ac001ed start_wqthread + 13
)
```

ss

It happened in various tests and at different times, so I can't really think of a rule when it crashes. Thoughts?

Thanks

### PR DESCRIPTION
**Pull request by sskhandp**
Fixes #491 and has been validated by @bootstraponline

### CODE REVIEW

File: EarlGrey/Additions/__NSCFLocalDataTask_GREYAdditions.m [hunk 1]
```diff
@@ -64,7 +64,7 @@ - (void)greyswizzled_resume {
     objc_setAssociatedObject(self,
                              @selector(greyswizzled_setState:),
                              elementID,
-                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
+                             OBJC_ASSOCIATION_RETAIN);
```
Comment (bootstraponline) [inline EarlGrey/Additions/__NSCFLocalDataTask_GREYAdditions.m]: It might be helpful to add a comment (something [like this](http://stackoverflow.com/a/29935110) to explain why retain is necessary to avoid the race condition.

Comment (sskhandp) [inline EarlGrey/Additions/__NSCFLocalDataTask_GREYAdditions.m]: Done

Comment (bootstraponline) [inline EarlGrey/Additions/__NSCFLocalDataTask_GREYAdditions.m]: Thanks!
