### PR TITLE
Fix further NSURLSession swizzling woes

### LINKED ISSUE #839: EarlGrey 1.0 | New Relic crash upon network swizzle
Following #710, a new issue was discovered when Earl Grey is linked together with New Relic.

The problem is here:
https://github.com/google/EarlGrey/blob/4a544a8c894fc7f93b954cd7297cad34ada0ed81/EarlGrey/Additions/NSURLSession%2BGREYAdditions.m#L65

The incorrect object is asked whether it responds to selector, causing a crash from `GREYFatalAssertWithMessage`.

I will submit a PR with a fix shortly.

### PR DESCRIPTION
**Pull request by LeoNatan**
Following #710, a new issue was discovered when Earl Grey is linked together with New Relic. This PR fixes the bug by actually selecting the correct `delegate` object and querying correctly if that object responds to the original selector.

Closes #839

### CODE REVIEW

**Comment by LeoNatan** [comment]
CC @khandpur @tirodkar 

Thanks

**Comment by LeoNatan** [comment]
@khandpur Fixd.

File: EarlGrey/Additions/NSURLSession+GREYAdditions.m [hunk 1]
```diff
@@ -54,19 +54,21 @@ - (NSURLSessionDataTask *)greyswizzled_dataTaskWithRequest:(NSURLRequest *)reque
...
   SEL originalSel = @selector(URLSession:task:didCompleteWithError:);
-  Class delegateClass =
-      [[delegate forwardingTargetForSelector:originalSel] class] ?: [delegate class];
-
+  // This is to solve issues where there is a proxy delegate instead of the original instance (e.g. TrustKit, New Relic).
+  // It responds YES to `respondsToSelector:` but `class_getInstanceMethod` returns nil.
+  // We attempt to follow the forwarding targets for the selector, if any exists.
+  id nextForwardingDelegate;
+  while ((nextForwardingDelegate = [delegate forwardingTargetForSelector:originalSel]))
+  {
```
Comment (khandpur) [inline EarlGrey/Additions/NSURLSession+GREYAdditions.m]: curly braces go on same line as per http://google.github.io/styleguide/objcguide.html

File: EarlGrey/Additions/NSURLSession+GREYAdditions.m [hunk 2]
```diff
@@ -54,19 +54,21 @@ - (NSURLSessionDataTask *)greyswizzled_dataTaskWithRequest:(NSURLRequest *)reque
   // Swizzle the session delegate class if not yet done.
   id delegate = self.delegate;
   SEL originalSel = @selector(URLSession:task:didCompleteWithError:);
-  Class delegateClass =
-      [[delegate forwardingTargetForSelector:originalSel] class] ?: [delegate class];
-
+  // This is to solve issues where there is a proxy delegate instead of the original instance (e.g. TrustKit, New Relic).
```
Comment (khandpur) [inline EarlGrey/Additions/NSURLSession+GREYAdditions.m]: max line length is 100 character. Could you break it off at that?
